site_name: UTMJBC Bot
repo_url: https://github.com/mrc2rules/UTMJBC-Bot
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/mrc2rules/UTMJBC-Bot/main/images/emailbot-border.png
  favicon: https://raw.githubusercontent.com/mrc2rules/UTMJBC-Bot/main/images/emailbot.png
  palette:
    scheme: default
    primary: black
    accent: yellow
  features:
    - navigation.tabs
nav:
  - 'index.md'
  - 'commands.md'
  - 'statistics.md'
  - 'status.md'
  - 'contributing.md'
  - 'legal.md'
