const { SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits } = require("discord.js");
const { getGeminiResponse } = require("../gemini/getGeminiResponse");

module.exports = {
    adminOnly: false,
    data: new SlashCommandBuilder()
        .setName("askai")
        .setDescription("Ask questions about UTM!")
        .setDefaultMemberPermissions(PermissionFlagsBits.SendMessages) // <-- added here
        .addStringOption(option =>
            option.setName("question")
                .setDescription("Your question")
                .setRequired(true)
        ),

    async execute(interaction) {
        const question = interaction.options.getString("question");

        await interaction.deferReply({ ephemeral: false });

        const result = await getGeminiResponse(question, interaction.guildId);

        if (!result) {
            return interaction.followUp({
                content: "⚠️ I couldn't get a response from Gemini. Please try again.",
                ephemeral: false
            });
        }

        const embed = new EmbedBuilder()
            .setColor(0x5D001A)
            .setTitle("AI Response")
            .setDescription(result.slice(0, 4096))
            .setFooter({ text: "This response was generated by AI and may or may not be accurate" });

        return interaction.followUp({
            embeds: [embed],
            ephemeral: false
        });
    }
};
